version: 0.0
os: linux

files:
  - source: /
    destination: /home/cd/user # 인스턴스에서 파일이 저장될 위치
permissions:
  - object: /home/cd/user
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStart:
    - location: user/scripts/deploy.sh
      timeout: 60
      runas: ec2-user